# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: postgres:13
        restart: always
        command: postgres -N 5000
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        volumes:
        - ./data:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        user: root
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
        - ./pgadmin:/var/lib/pgadmin
        ports:
        - 5050:80
        restart: unless-stopped

